### PR TITLE
Use webrtc for coder sh

### PR DESCRIPTION
**Pull request by Emyrk**
# What this does

Uses webrtc for `coder sh`

### CODE REVIEW

**Review by f0ssel — APPROVED** [review]

**Comment by Emyrk** [comment]
@deansheather @f0ssel This would likely break any v1 providers. I'm guessing we already released the CLI for the last release so I can merge this yes?

**Comment by f0ssel** [comment]
Yup this will be save for 1.22

**Review by kylecarbs — CHANGES_REQUESTED** [review]
It might be cleaner to move our options into a map. That way, we could use them for `config-ssh` along with `coder sh`.

**Comment by Emyrk** [comment]
@kylecarbs That sort of solves things, but the quoting was also different for the two cases. 

A more general solution would nice, I didn't try and tackle that here.

**Review by kylecarbs — APPROVED** [review]
Try to merge master in first... I changed some stuff up with the options that will conflict here!

**Pull request merged**
