### PR TITLE
Rename environments to workspaces and use new routes

### PR DESCRIPTION
**Pull request by code-asher**
Also closes [ch5518].

### CODE REVIEW

**Review by f0ssel — APPROVED** [review]
Has anyone else been looped in on the command change from `coder envs` to `coder ws`? I know we have been using that shorthand internally but since this is an customer command I'd wanna make sure others are on board. I don't hate `workspaces` but I do see it's long.

**Comment by kylecarbs** [comment]
We should do both workspaces and ws imo.

**Comment by code-asher** [comment]
Currently I have `workspaces` as an alias for `ws` but I think the reverse might actually make more sense.

**Comment by code-asher** [comment]
Swapped! We use `workspaces` everywhere now including documentation but `ws` is a valid alias to use in its place. I think this is quite a bit more clear especially since `ws` often means `websocket`, at least in the codebase.

**Comment by kylecarbs** [comment]
✨

**Review by f0ssel — APPROVED** [review]
:pray:

**Pull request merged**
